//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vols.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.userJob = new HashSet<userJob>();
        }
    
        public int jobID { get; set; }
        public double locationLat { get; set; }
        public double locationLong { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string description { get; set; }
        public int numVolsNeed { get; set; }
        public int createdBy { get; set; }
    
        public virtual user user { get; set; }
        public virtual jobPics jobPics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userJob> userJob { get; set; }
    }
}
